export const SITE_URL = process.env.NEXT_PUBLIC_APP_URL ?? 'https://rickjeffersonsolutions.com'
export const CALENDLY_URL = process.env.NEXT_PUBLIC_CALENDLY_URL ?? 'https://calendly.com/rickjefferson/cro-partner'

export const TIERS = [
  {
    id:          'starter',
    name:        'Starter',
    emoji:       '🚀',
    tag:         null,
    minFiles:    10,
    pricePerFile: 47,
    monthlyMin:  470,
    turnaround:  '48 hours',
    color:       'from-slate-500 to-slate-400',
    borderColor: 'border-slate-500/30',
    glowColor:   'rgba(100,116,139,0.2)',
    stripeEnvKey: 'STRIPE_PRICE_STARTER',
    features: [
      '10-category FCRA violation analysis',
      'Detailed violation report + severity ratings',
      'Statutory damages calculations',
      '3 Bureau dispute letters (all bureaus)',
      'Basic 5-point financial roadmap',
      '48-hour turnaround',
      'PDF + TXT email delivery',
    ],
    notIncluded: [
      'White-label branding',
      'Priority processing',
      'Dedicated account manager',
    ],
  },
  {
    id:          'professional',
    name:        'Professional',
    emoji:       '⭐',
    tag:         'Most Popular',
    minFiles:    25,
    pricePerFile: 37,
    monthlyMin:  925,
    turnaround:  '24 hours',
    color:       'from-violet-600 to-cyan-500',
    borderColor: 'border-violet-500/50',
    glowColor:   'rgba(99,91,255,0.25)',
    stripeEnvKey: 'STRIPE_PRICE_PROFESSIONAL',
    features: [
      'Everything in Starter',
      'White-label branding (your logo + name)',
      'Complete 10-point financial roadmap',
      'Round 2 escalation letters included',
      '24-hour turnaround',
      'Priority support',
      'Monthly performance reports',
      'API access (beta)',
      'Custom letterhead integration',
    ],
    notIncluded: [],
  },
  {
    id:          'enterprise',
    name:        'Enterprise',
    emoji:       '🏢',
    tag:         'Best Value',
    minFiles:    100,
    pricePerFile: 27,
    monthlyMin:  2700,
    turnaround:  '12 hours',
    color:       'from-blue-600 to-violet-600',
    borderColor: 'border-blue-500/50',
    glowColor:   'rgba(37,99,235,0.25)',
    stripeEnvKey: 'STRIPE_PRICE_ENTERPRISE',
    features: [
      'Everything in Professional',
      'Dedicated account manager',
      '12-hour turnaround (rush available)',
      'Round 3 pre-litigation letters included',
      'Federal court complaint drafting (+$97/doc)',
      'Phone support',
      'Quarterly business reviews',
      'Custom integrations (Zapier, webhooks)',
      'Bulk upload portal',
      'Real-time status dashboard',
      '5% discount at 200+ files/month',
      '10% discount at 500+ files/month',
    ],
    notIncluded: [],
  },
  {
    id:          'platinum',
    name:        'Platinum Partner',
    emoji:       '💎',
    tag:         'Elite',
    minFiles:    500,
    pricePerFile: 22,
    monthlyMin:  11000,
    turnaround:  '6 hours',
    color:       'from-amber-400 to-orange-500',
    borderColor: 'border-amber-400/50',
    glowColor:   'rgba(251,191,36,0.2)',
    stripeEnvKey: 'STRIPE_PRICE_PLATINUM',
    features: [
      'Everything in Enterprise',
      '6-hour standard turnaround',
      '2-hour rush available (+$15/file)',
      'Unlimited revisions',
      'White-glove onboarding + team training',
      'Dedicated processing team',
      'Custom workflow automation',
      'Multi-location support',
      'Reseller rights (sublicense to CROs)',
      'Revenue sharing opportunities',
      'Territory exclusivity (negotiable)',
      'Joint marketing campaigns',
      '24/7 emergency phone support',
    ],
    notIncluded: [],
  },
] as const

export const ADDONS = [
  { name: 'Rush Processing (6hr)',   price: 15,  note: 'Professional+' },
  { name: 'Rush Processing (2hr)',   price: 35,  note: 'Platinum only' },
  { name: 'Round 2 Letters',         price: 12,  note: 'All 3 bureaus' },
  { name: 'Round 3 Pre-Litigation',  price: 18,  note: 'Attorney-level' },
  { name: 'Federal Court Complaint', price: 97,  note: 'FCRA/FDCPA' },
  { name: 'CFPB Complaint Draft',    price: 47,  note: 'Regulatory' },
  { name: 'State AG Complaint',      price: 47,  note: 'State-level' },
  { name: 'Debt Validation Letters', price: 12,  note: 'FDCPA §1692g' },
  { name: 'Pay-for-Delete Letter',   price: 15,  note: 'Settlement' },
  { name: 'Goodwill Letter',         price: 12,  note: 'Late payment' },
  { name: 'Cease & Desist',          price: 15,  note: 'Stop collectors' },
  { name: 'Identity Theft Package',  price: 67,  note: 'Full recovery' },
  { name: 'Credit Repair Roadmap',   price: 27,  note: '10-point plan' },
  { name: 'Business Credit Analysis',price: 47,  note: 'D&B / Exp Biz' },
  { name: 'Business Funding Package',price: 77,  note: 'Loan prep docs' },
  { name: 'Mortgage Readiness Report',price: 37, note: 'FHA/Conventional' },
] as const

export const VOLUME_TIERS = [
  { min: 25,   max: 49,   price: 37, savings: 0 },
  { min: 50,   max: 99,   price: 34, savings: 8 },
  { min: 100,  max: 199,  price: 27, savings: 27 },
  { min: 200,  max: 499,  price: 25, savings: 32 },
  { min: 500,  max: 999,  price: 22, savings: 41 },
  { min: 1000, max: null, price: null, savings: 45 },
] as const

export const STATS = [
  { value: '99.7%', label: 'Detection Accuracy' },
  { value: '48hr',  label: 'Max Turnaround' },
  { value: '10',    label: 'FCRA Categories' },
  { value: '$0',    label: 'Setup Fee (Enterprise+)' },
] as const

export const LAUNCH_OFFERS = [
  { code: 'LAUNCH50',     label: '50% Off First Month',   desc: 'Any tier, new partners only' },
  { code: 'WHITELABEL',   label: 'Free White-Label Setup', desc: 'Save $297 setup fee (Professional+)' },
  { code: 'ENTERPRISE10', label: '10 Free Files',          desc: 'Enterprise sign-ups, first month' },
  { code: 'REFER-A-CRO',  label: '$500 Referral Credit',   desc: 'Unlimited referrals, no cap' },
] as const
